---
name: Pull Request
on:
  pull_request:
      branches:
        - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: '@stephanieea'
  
      - name: install
        run: npm ci
    
      - name: delete old package versions
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl -s -N POST https://api.github.com/graphql \
          -H "Authorization: bearer $NODE_AUTH_TOKEN" \
          -d '{"query":"query{repository(owner:\"stephanieea\",name:\"changesets-playground\"){packages(first:100){nodes{name,id,versions(first:100){nodes{id,version}}}}}}"}' \
          | jq -r --arg PR "PR-$PR_NUMBER" '.data.repository.packages.nodes[].versions.nodes[] 
          | select(.version | contains($PR)) 
          | .id' \
          | while read object; do \
            curl -X POST https://api.github.com/graphql \
              -H "Accept: application/vnd.github.package-deletes-preview+json" \
              -H "Authorization: bearer $NODE_AUTH_TOKEN "\
              -d '{"query":"mutation { deletePackageVersion(input:{packageVersionId:'\\\"${object}\\\"'}) { success }}"}'; \
          done

      - name: Update Version
        id: update-version
        continue-on-error: true # there may be an expected error when trying to publish a package version over existing version
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          version=PR-${PR_NUMBER}-${PR_HEAD_SHA:0:7}
          error=$(npx changeset version --snapshot $VERSION 2>&1 >/dev/null)
          [[ $error == *"No unreleased changesets found"* ]] && hasChangesets="false" || hasChangesets="true"
          echo '::set-output name=hasChangesets::${hasChangesets}'

        # Update package-lock.json with changeset version
      - name: Install Updated Package(s)
        id: install-updated-packages
        if: steps.update-version.outputs.hasChangesets == 'true'
        run: npm install --package-lock-only

      - name: Publish Version
        if: steps.update-version.outputs.hasChangesets == 'true'
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          version=PR-${PR_NUMBER}-${PR_HEAD_SHA:0:7}
          npx @changesets/cli publish --tag $version
...
