---
name: Pull Request
on:
  pull_request:
      branches:
        - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          # ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: '@stephanieea'

      - name: Get Node Version
        id: node-version
        run: |
          NODE_VERSION=$(node -v)
          echo "::set-output name=NODE_VERSION::$NODE_VERSION"
  
      - name: Get Changesets Version
        id: changesets-version
        run: |
          CHANGESETS_VERSION=$(npm show @changesets/cli version)
          echo "::set-output name=CHANGESETS_VERSION::$CHANGESETS_VERSION"

      - name: Cache Changesets
        id: cache-changesets
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ steps.node-version.outputs.NODE_VERSION }}-${{ steps.changesets-version.outputs.CHANGESETS_VERSION }}-changesets }}



      - name: delete old package versions
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl -s -N POST https://api.github.com/graphql \
          -H "Authorization: bearer $NODE_AUTH_TOKEN" \
          -d '{"query":"query{repository(owner:\"stephanieea\",name:\"changesets-playground\"){packages(first:100){nodes{name,id,versions(first:100){nodes{id,version}}}}}}"}' \
          | jq -r --arg PR "PR-$PR_NUMBER" '.data.repository.packages.nodes[].versions.nodes[] 
          | select(.version | contains($PR)) 
          | .id' \
          | while read object; do \
            curl -X POST https://api.github.com/graphql \
              -H "Accept: application/vnd.github.package-deletes-preview+json" \
              -H "Authorization: bearer $NODE_AUTH_TOKEN "\
              -d '{"query":"mutation { deletePackageVersion(input:{packageVersionId:'\\\"${object}\\\"'}) { success }}"}'; \
          done

      - name: Install Changesets Only
        if: steps.cache-changesets.outputs.cache-hit != 'true'
        run: | 
          npm uninstall *
          npm install @changesets/cli

      - name: tree
        run: tree -a

      - name: Update and Publish Version
        id: update-publish-version
        continue-on-error: true # there may be an expected error when trying to publish a package version over existing version
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          version=PR-${PR_NUMBER}-${PR_HEAD_SHA:0:7}
          npx cowsay "goodbye"
          npx @changesets/cli version --snapshot $version
          npx @changesets/cli publish --tag $version
...
