name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm ci 

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ---
# name: Release
# on:
#   release:
#     types: [created]
      
# jobs:
#   publish-gpr:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: write
#     if: github.ref_type == 'tag'
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: main
#       - uses: actions/setup-node@v2
#         with:
#           node-version: lts/*
#           registry-url: https://npm.pkg.github.com/
#           scope: '@stephanieea'
#       - run: npm ci
#       - name: Pubish Patch
#         id: publish-patch
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           npm version ${{ github.event.release.tag_name }} --allow-same-version
#           git push
#           npm publish --access public
# ...